print('Agora é a vez da tabuada')
n = float(input('Qual o número que você gostaria de saber a tabuada?'))
print('-' * 12)
print('Vamos Lá, a tabuada de {} é:'.format(n))
print('{} * 1 = {}'.format(n, n*1))
print('{} * 2 = {}'.format(n, n*2))
print('{} * 3 = {}'.format(n, n*3))
print('{} * 4 = {}'.format(n, n*4))
print('{} * 5 = {}'.format(n, n*5))
print('{} * 6 = {}'.format(n, n*6))
print('{} * 7 = {}'. format(n, n*7))
print('{} * 8 = {}'.format(n, n*8))
print('{} * 9 = {}'.format(n, n*9))
print('{} * 10 = {}'.format(n, n*10))
print('-' * 12)
n1 = float(input('Caso queira multiplicar por outro valor, digite aqui:'))
print('O resultado é igual a {:.2f}'.format(n*n1))
