print('Farei a converão de metros para centimeros, milímetros e quilometros')
m = float(input('Qual a distância em metros?'))
print('Essa distância corresponde a:')
print('{}mm'.format(m*1000))
print('{}cm'.format(m*100))
print('{}dm'.format(m*10))
print('{}dam'.format(m/10))
print('{}hm'.format(m/100))
print('{}km'.format(m/1000))
