nome = input('Qual é o seu nome?').strip().capitalize()
print('Seja muito bem vindo {}-chan!'.format(nome))
div = input('Oque iremos fazer hoje {}-chan ?'.format(nome)).strip()
print('Que demais, dê o seu melhor {}-chan'.format(nome))
input('Você gosta de filmes {}-chan?'.format(nome))
anime = input('Qual filme você gosta mais {}-chan?'.format(nome)).strip()
print('{} é realmente  muito bom'.format(anime))
input('Eu sei fazer contas, gostaria de ver?')
n1 = float(input('Vamos lá, digite um número:'))
n2 = float(input('Agora mais um, por favor:'))
print('A soma de {} e {} é igual á {} {}-chan'.format(n1, n2, n1+n2, nome))
idade = input('Quantos anos você tem {}?'.format(nome))
print('Ah sim, então você tem {} anos {}-chan'.format(idade, nome))
print('Eu estou em processo de criação ainda (;-;) então não tenho uma idade definida')
input('Posso {} com você?'.format(div))
input('você pode me ensinar?')
print('Você é mutio gentil {}-chan'.format(nome))
print('Lembra dos números que você me deu {}-chan, vou calcular a divisão inteira deles'.format(nome))
print('A divisao de {} por {} resulta em {} com um resto de {}'.format(n1, n2, n1//n2, n1%n2))
import playsound
print('Eu aprendi a tocar músicas {}-chan'.format(nome))
input('Posso reproduzi-la?')
print('Vamos lá então')
playsound.playsound('ex021.mp3')
import emoji
print(emoji.emojize('Eu amo essa música :heart:', use_aliases=True))
print('Vou analisar umas coisas sobre o seu nome (:3)')
nome2 = nome.upper()
print('Existem {} letras A no seu nome'.format(nome2.count('A')))
print('E ela aparece pela primeira vez na posição {}'.format(nome2.find('A')+1))

