n = input('Vamos testar uma coisa, digite algo:')
print('{} é númerico?'.format(n), n.isnumeric())
print('Qual é o tipo de {}'.format(n), type(n))
print('{} é alfabético?'.format(n), n.isalpha())
print('{} é imprimivel?'.format(n), n.isprintable())
print('{} é alpha-numerico?'.format(n), n.isalnum())
print('{} esta somente com letras maiusculas?'.format(n),n.isupper())
print('{} é todo minúsculo?'.format(n), n.islower())
print('{} é somente espaços?'.format(n), n.isspace())
print('{} está capitalizada?'.format(n), n.istitle())
